print("Prencha os campos abaixo para descobrir seu IMC (Indice de Massa Corporal")
peso = float(input("Peso:"))
altura = float(input("Altura:"))
resultado = float(peso/(altura*altura))
print(resultado)
